# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/googleapis/gnostic/surface/surface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/googleapis/gnostic/surface/surface.proto',
  package='surface.v1',
  syntax='proto3',
  serialized_pb=_b('\n3github.com/googleapis/gnostic/surface/surface.proto\x12\nsurface.v1\"\xd1\x01\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12#\n\x04kind\x18\x03 \x01(\x0e\x32\x15.surface.v1.FieldKind\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12&\n\x08position\x18\x05 \x01(\x0e\x32\x14.surface.v1.Position\x12\x12\n\nnativeType\x18\x06 \x01(\t\x12\x11\n\tfieldName\x18\x07 \x01(\t\x12\x15\n\rparameterName\x18\x08 \x01(\t\x12\x11\n\tserialize\x18\t \x01(\x08\"\x97\x01\n\x04Type\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04kind\x18\x02 \x01(\x0e\x32\x14.surface.v1.TypeKind\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0b\x63ontentType\x18\x04 \x01(\t\x12!\n\x06\x66ields\x18\x05 \x03(\x0b\x32\x11.surface.v1.Field\x12\x10\n\x08typeName\x18\x06 \x01(\t\"\xd3\x01\n\x06Method\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x13\n\x0bhandlerName\x18\x06 \x01(\t\x12\x15\n\rprocessorName\x18\x07 \x01(\t\x12\x12\n\nclientName\x18\x08 \x01(\t\x12\x1a\n\x12parametersTypeName\x18\t \x01(\t\x12\x19\n\x11responsesTypeName\x18\n \x01(\t\"[\n\x05Model\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x05types\x18\x02 \x03(\x0b\x32\x10.surface.v1.Type\x12#\n\x07methods\x18\x03 \x03(\x0b\x32\x12.surface.v1.Method*:\n\tFieldKind\x12\n\n\x06SCALAR\x10\x00\x12\x07\n\x03MAP\x10\x01\x12\t\n\x05\x41RRAY\x10\x02\x12\r\n\tREFERENCE\x10\x03*\"\n\x08TypeKind\x12\n\n\x06STRUCT\x10\x00\x12\n\n\x06OBJECT\x10\x01*C\n\x08Position\x12\x08\n\x04\x42ODY\x10\x00\x12\n\n\x06HEADER\x10\x01\x12\x0c\n\x08\x46ORMDATA\x10\x02\x12\t\n\x05QUERY\x10\x03\x12\x08\n\x04PATH\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FIELDKIND = _descriptor.EnumDescriptor(
  name='FieldKind',
  full_name='surface.v1.FieldKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCALAR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARRAY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REFERENCE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=740,
  serialized_end=798,
)
_sym_db.RegisterEnumDescriptor(_FIELDKIND)

FieldKind = enum_type_wrapper.EnumTypeWrapper(_FIELDKIND)
_TYPEKIND = _descriptor.EnumDescriptor(
  name='TypeKind',
  full_name='surface.v1.TypeKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRUCT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBJECT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=800,
  serialized_end=834,
)
_sym_db.RegisterEnumDescriptor(_TYPEKIND)

TypeKind = enum_type_wrapper.EnumTypeWrapper(_TYPEKIND)
_POSITION = _descriptor.EnumDescriptor(
  name='Position',
  full_name='surface.v1.Position',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BODY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEADER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORMDATA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PATH', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=836,
  serialized_end=903,
)
_sym_db.RegisterEnumDescriptor(_POSITION)

Position = enum_type_wrapper.EnumTypeWrapper(_POSITION)
SCALAR = 0
MAP = 1
ARRAY = 2
REFERENCE = 3
STRUCT = 0
OBJECT = 1
BODY = 0
HEADER = 1
FORMDATA = 2
QUERY = 3
PATH = 4



_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='surface.v1.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='surface.v1.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='surface.v1.Field.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='surface.v1.Field.kind', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='surface.v1.Field.format', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='surface.v1.Field.position', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nativeType', full_name='surface.v1.Field.nativeType', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fieldName', full_name='surface.v1.Field.fieldName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameterName', full_name='surface.v1.Field.parameterName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serialize', full_name='surface.v1.Field.serialize', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=277,
)


_TYPE = _descriptor.Descriptor(
  name='Type',
  full_name='surface.v1.Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='surface.v1.Type.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='surface.v1.Type.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='surface.v1.Type.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contentType', full_name='surface.v1.Type.contentType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='surface.v1.Type.fields', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='typeName', full_name='surface.v1.Type.typeName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=431,
)


_METHOD = _descriptor.Descriptor(
  name='Method',
  full_name='surface.v1.Method',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='surface.v1.Method.operation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='surface.v1.Method.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='surface.v1.Method.method', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='surface.v1.Method.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='surface.v1.Method.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='handlerName', full_name='surface.v1.Method.handlerName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processorName', full_name='surface.v1.Method.processorName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientName', full_name='surface.v1.Method.clientName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parametersTypeName', full_name='surface.v1.Method.parametersTypeName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responsesTypeName', full_name='surface.v1.Method.responsesTypeName', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=645,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='surface.v1.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='surface.v1.Model.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='types', full_name='surface.v1.Model.types', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='methods', full_name='surface.v1.Model.methods', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=738,
)

_FIELD.fields_by_name['kind'].enum_type = _FIELDKIND
_FIELD.fields_by_name['position'].enum_type = _POSITION
_TYPE.fields_by_name['kind'].enum_type = _TYPEKIND
_TYPE.fields_by_name['fields'].message_type = _FIELD
_MODEL.fields_by_name['types'].message_type = _TYPE
_MODEL.fields_by_name['methods'].message_type = _METHOD
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['Type'] = _TYPE
DESCRIPTOR.message_types_by_name['Method'] = _METHOD
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.enum_types_by_name['FieldKind'] = _FIELDKIND
DESCRIPTOR.enum_types_by_name['TypeKind'] = _TYPEKIND
DESCRIPTOR.enum_types_by_name['Position'] = _POSITION

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'github.com.googleapis.gnostic.surface.surface_pb2'
  # @@protoc_insertion_point(class_scope:surface.v1.Field)
  ))
_sym_db.RegisterMessage(Field)

Type = _reflection.GeneratedProtocolMessageType('Type', (_message.Message,), dict(
  DESCRIPTOR = _TYPE,
  __module__ = 'github.com.googleapis.gnostic.surface.surface_pb2'
  # @@protoc_insertion_point(class_scope:surface.v1.Type)
  ))
_sym_db.RegisterMessage(Type)

Method = _reflection.GeneratedProtocolMessageType('Method', (_message.Message,), dict(
  DESCRIPTOR = _METHOD,
  __module__ = 'github.com.googleapis.gnostic.surface.surface_pb2'
  # @@protoc_insertion_point(class_scope:surface.v1.Method)
  ))
_sym_db.RegisterMessage(Method)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'github.com.googleapis.gnostic.surface.surface_pb2'
  # @@protoc_insertion_point(class_scope:surface.v1.Model)
  ))
_sym_db.RegisterMessage(Model)


# @@protoc_insertion_point(module_scope)
