// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apisjson.proto

/*
Package apisjson_v1 is a generated protocol buffer package.

It is generated from these files:
	apisjson.proto

It has these top-level messages:
	Any
	Api
	Document
	Include
	Maintainer
	Property
	StringArray
*/
package apisjson_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Any struct {
	Value *google_protobuf.Any `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Yaml  string               `protobuf:"bytes,2,opt,name=yaml" json:"yaml,omitempty"`
}

func (m *Any) Reset()                    { *m = Any{} }
func (m *Any) String() string            { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()               {}
func (*Any) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Any) GetValue() *google_protobuf.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Any) GetYaml() string {
	if m != nil {
		return m.Yaml
	}
	return ""
}

// An API description.
type Api struct {
	Name        string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Image       string        `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	HumanURL    string        `protobuf:"bytes,4,opt,name=human_u_r_l,json=humanURL" json:"human_u_r_l,omitempty"`
	BaseURL     string        `protobuf:"bytes,5,opt,name=base_u_r_l,json=baseURL" json:"base_u_r_l,omitempty"`
	Version     string        `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
	Tags        []string      `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty"`
	Properties  []*Property   `protobuf:"bytes,8,rep,name=properties" json:"properties,omitempty"`
	Contact     []*Maintainer `protobuf:"bytes,9,rep,name=contact" json:"contact,omitempty"`
}

func (m *Api) Reset()                    { *m = Api{} }
func (m *Api) String() string            { return proto.CompactTextString(m) }
func (*Api) ProtoMessage()               {}
func (*Api) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Api) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Api) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Api) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Api) GetHumanURL() string {
	if m != nil {
		return m.HumanURL
	}
	return ""
}

func (m *Api) GetBaseURL() string {
	if m != nil {
		return m.BaseURL
	}
	return ""
}

func (m *Api) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Api) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Api) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Api) GetContact() []*Maintainer {
	if m != nil {
		return m.Contact
	}
	return nil
}

type Document struct {
	// text string of human readable name for the collection of APIs
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// text human readable description of the collection of APIs
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// web URL leading to an image to be used to represent the collection of APIs defined in this file
	Image string `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	// Web URL indicating the location of the latest version of this file
	Url string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	// this is a list of descriptive strings which identify the contents of the APIs.json file. Represented as an array
	Tags                 []string      `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Created              string        `protobuf:"bytes,6,opt,name=created" json:"created,omitempty"`
	Modified             string        `protobuf:"bytes,7,opt,name=modified" json:"modified,omitempty"`
	SpecificationVersion string        `protobuf:"bytes,8,opt,name=specification_version,json=specificationVersion" json:"specification_version,omitempty"`
	Apis                 []*Api        `protobuf:"bytes,9,rep,name=apis" json:"apis,omitempty"`
	Include              []*Include    `protobuf:"bytes,10,rep,name=include" json:"include,omitempty"`
	Maintainers          []*Maintainer `protobuf:"bytes,11,rep,name=maintainers" json:"maintainers,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Document) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Document) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Document) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Document) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *Document) GetSpecificationVersion() string {
	if m != nil {
		return m.SpecificationVersion
	}
	return ""
}

func (m *Document) GetApis() []*Api {
	if m != nil {
		return m.Apis
	}
	return nil
}

func (m *Document) GetInclude() []*Include {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *Document) GetMaintainers() []*Maintainer {
	if m != nil {
		return m.Maintainers
	}
	return nil
}

type Include struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *Include) Reset()                    { *m = Include{} }
func (m *Include) String() string            { return proto.CompactTextString(m) }
func (*Include) ProtoMessage()               {}
func (*Include) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Include) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Include) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Maintainer struct {
	Fn       string `protobuf:"bytes,1,opt,name=fn" json:"fn,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Org      string `protobuf:"bytes,4,opt,name=org" json:"org,omitempty"`
	Adr      string `protobuf:"bytes,5,opt,name=adr" json:"adr,omitempty"`
	Tel      string `protobuf:"bytes,6,opt,name=tel" json:"tel,omitempty"`
	XTwitter string `protobuf:"bytes,7,opt,name=x_twitter,json=xTwitter" json:"x_twitter,omitempty"`
	XGithub  string `protobuf:"bytes,8,opt,name=x_github,json=xGithub" json:"x_github,omitempty"`
	Photo    string `protobuf:"bytes,9,opt,name=photo" json:"photo,omitempty"`
	Vcard    string `protobuf:"bytes,10,opt,name=vcard" json:"vcard,omitempty"`
}

func (m *Maintainer) Reset()                    { *m = Maintainer{} }
func (m *Maintainer) String() string            { return proto.CompactTextString(m) }
func (*Maintainer) ProtoMessage()               {}
func (*Maintainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Maintainer) GetFn() string {
	if m != nil {
		return m.Fn
	}
	return ""
}

func (m *Maintainer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Maintainer) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Maintainer) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *Maintainer) GetAdr() string {
	if m != nil {
		return m.Adr
	}
	return ""
}

func (m *Maintainer) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *Maintainer) GetXTwitter() string {
	if m != nil {
		return m.XTwitter
	}
	return ""
}

func (m *Maintainer) GetXGithub() string {
	if m != nil {
		return m.XGithub
	}
	return ""
}

func (m *Maintainer) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *Maintainer) GetVcard() string {
	if m != nil {
		return m.Vcard
	}
	return ""
}

type Property struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Property) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Property) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StringArray struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *StringArray) Reset()                    { *m = StringArray{} }
func (m *StringArray) String() string            { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()               {}
func (*StringArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StringArray) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Any)(nil), "apisjson.v1.Any")
	proto.RegisterType((*Api)(nil), "apisjson.v1.Api")
	proto.RegisterType((*Document)(nil), "apisjson.v1.Document")
	proto.RegisterType((*Include)(nil), "apisjson.v1.Include")
	proto.RegisterType((*Maintainer)(nil), "apisjson.v1.Maintainer")
	proto.RegisterType((*Property)(nil), "apisjson.v1.Property")
	proto.RegisterType((*StringArray)(nil), "apisjson.v1.StringArray")
}

func init() { proto.RegisterFile("apisjson.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0x56, 0x1c, 0xc9, 0xa3, 0x92, 0x86, 0xc5, 0xa1, 0x9b, 0x84, 0x82, 0x51, 0x0b, 0x0d,
	0x3d, 0x28, 0x24, 0xa1, 0x87, 0x1e, 0x15, 0xfa, 0x41, 0xa0, 0x25, 0x46, 0x69, 0x7b, 0x15, 0x6b,
	0x69, 0xad, 0x6c, 0xb1, 0x76, 0xc5, 0x6a, 0xe5, 0x5a, 0x7f, 0xa7, 0xd0, 0xbf, 0xd5, 0xdf, 0xd1,
	0x63, 0xd9, 0x0f, 0x39, 0x36, 0x2d, 0x3d, 0xf5, 0x36, 0x6f, 0xde, 0x9b, 0xd1, 0xe8, 0xcd, 0xb0,
	0x70, 0x40, 0x6a, 0xd6, 0x7c, 0x6d, 0x04, 0x8f, 0x6b, 0x29, 0x94, 0x40, 0xe1, 0x06, 0xaf, 0x2e,
	0x4e, 0x8e, 0x4b, 0x21, 0xca, 0x25, 0x3d, 0x37, 0xd4, 0xbc, 0x5d, 0x9c, 0x13, 0xde, 0x59, 0x5d,
	0xf4, 0x16, 0xbc, 0x84, 0x77, 0xe8, 0x25, 0x8c, 0x56, 0x64, 0xd9, 0x52, 0x3c, 0x98, 0x0e, 0xce,
	0xc2, 0xcb, 0x49, 0x6c, 0x2b, 0xe2, 0xbe, 0x22, 0x4e, 0x78, 0x97, 0x5a, 0x09, 0x42, 0xb0, 0xd7,
	0x91, 0x6a, 0x89, 0x87, 0xd3, 0xc1, 0xd9, 0x38, 0x35, 0x71, 0xf4, 0x63, 0x08, 0x5e, 0x52, 0x33,
	0xcd, 0x71, 0x52, 0xd9, 0x36, 0xe3, 0xd4, 0xc4, 0x68, 0x0a, 0x61, 0x41, 0x9b, 0x5c, 0xb2, 0x5a,
	0x31, 0xc1, 0x5d, 0xd9, 0x76, 0x0a, 0x4d, 0x60, 0xc4, 0x2a, 0x52, 0x52, 0xec, 0x19, 0xce, 0x02,
	0xf4, 0x14, 0xc2, 0xfb, 0xb6, 0x22, 0x3c, 0x6b, 0x33, 0x99, 0x2d, 0xf1, 0x9e, 0xe1, 0x02, 0x93,
	0xfa, 0x9c, 0x7e, 0x40, 0xa7, 0x00, 0x73, 0xd2, 0x50, 0xc7, 0x8e, 0x0c, 0xeb, 0xeb, 0x8c, 0x26,
	0x31, 0xf8, 0x2b, 0x2a, 0x1b, 0xfd, 0xbd, 0x7d, 0xcb, 0x38, 0xa8, 0x27, 0x54, 0xa4, 0x6c, 0xb0,
	0x3f, 0xf5, 0xf4, 0x84, 0x3a, 0x46, 0xaf, 0x00, 0x6a, 0x29, 0x6a, 0x2a, 0x15, 0xa3, 0x0d, 0x0e,
	0xa6, 0xde, 0x59, 0x78, 0x79, 0x14, 0x6f, 0x39, 0x18, 0xcf, 0x2c, 0xdd, 0xa5, 0x5b, 0x42, 0x74,
	0x01, 0x7e, 0x2e, 0xb8, 0x22, 0xb9, 0xc2, 0x63, 0x53, 0xf3, 0x64, 0xa7, 0xe6, 0x23, 0x61, 0x5c,
	0x11, 0xc6, 0xa9, 0x4c, 0x7b, 0x5d, 0xf4, 0x6b, 0x08, 0xc1, 0x1b, 0x91, 0xb7, 0x15, 0xe5, 0xea,
	0xbf, 0x9a, 0x75, 0x08, 0x5e, 0x2b, 0x7b, 0x93, 0x74, 0xb8, 0xf9, 0xd1, 0xd1, 0xd6, 0x8f, 0x62,
	0xf0, 0x73, 0x49, 0x89, 0xa2, 0x45, 0x6f, 0x8b, 0x83, 0xe8, 0x04, 0x82, 0x4a, 0x14, 0x6c, 0xc1,
	0x68, 0x81, 0x7d, 0xeb, 0x74, 0x8f, 0xd1, 0x15, 0x1c, 0x35, 0x35, 0xcd, 0xd9, 0x82, 0xe5, 0x44,
	0x8f, 0x90, 0xf5, 0xd6, 0x06, 0x46, 0x38, 0xd9, 0x21, 0xbf, 0x38, 0x9f, 0x9f, 0xc3, 0x9e, 0x36,
	0xc3, 0x39, 0x73, 0xb8, 0xe3, 0x4c, 0x52, 0xb3, 0xd4, 0xb0, 0x28, 0x06, 0x9f, 0xf1, 0x7c, 0xd9,
	0x16, 0x14, 0x83, 0x11, 0x4e, 0x76, 0x84, 0x37, 0x96, 0x4b, 0x7b, 0x11, 0x7a, 0x0d, 0x61, 0xb5,
	0xb1, 0xb5, 0xc1, 0xe1, 0xbf, 0x6d, 0xdf, 0xd6, 0x46, 0xe7, 0xe0, 0xbb, 0x76, 0x7f, 0x35, 0xde,
	0x19, 0x38, 0xdc, 0x18, 0x18, 0xfd, 0x1c, 0x00, 0x3c, 0x34, 0x43, 0x07, 0x30, 0x5c, 0x70, 0x57,
	0x32, 0x5c, 0x98, 0x3d, 0xd0, 0x8a, 0xb0, 0xbe, 0xc4, 0x82, 0xbe, 0x8d, 0xf7, 0xb0, 0x87, 0x43,
	0xf0, 0x84, 0x2c, 0xfb, 0xcd, 0x08, 0x59, 0xea, 0x0c, 0x29, 0xa4, 0x3b, 0x59, 0x1d, 0xea, 0x8c,
	0xa2, 0x4b, 0xb7, 0x13, 0x1d, 0xa2, 0x53, 0x18, 0xaf, 0x33, 0xf5, 0x8d, 0x29, 0x45, 0x65, 0xbf,
	0x90, 0xf5, 0x27, 0x8b, 0xd1, 0x31, 0x04, 0xeb, 0xac, 0x64, 0xea, 0xbe, 0x9d, 0xbb, 0x1d, 0xf8,
	0xeb, 0xf7, 0x06, 0xea, 0xa9, 0xea, 0x7b, 0xa1, 0x04, 0x1e, 0xdb, 0xa9, 0x0c, 0xd0, 0xd9, 0x55,
	0x4e, 0x64, 0x81, 0xc1, 0x66, 0x0d, 0x88, 0xde, 0x41, 0xd0, 0xdf, 0xb5, 0xb9, 0x96, 0xae, 0xde,
	0x58, 0xa2, 0xe3, 0x3f, 0x2d, 0x31, 0x7d, 0xcc, 0x33, 0xe1, 0x6e, 0xcf, 0x80, 0xe8, 0x19, 0x84,
	0x77, 0x4a, 0x32, 0x5e, 0x26, 0x52, 0x92, 0xee, 0x41, 0x34, 0x30, 0x97, 0x67, 0xc1, 0xf5, 0x0b,
	0x78, 0x2c, 0x64, 0xb9, 0xd9, 0x54, 0xb6, 0xba, 0xb8, 0x7e, 0x74, 0x5b, 0x53, 0x9e, 0xcc, 0x6e,
	0x66, 0xfa, 0x91, 0x99, 0x0d, 0xbe, 0x0f, 0xbd, 0xdb, 0xe4, 0x6e, 0xbe, 0x6f, 0xde, 0x9c, 0xab,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x65, 0xf7, 0xc0, 0xd2, 0x04, 0x00, 0x00,
}
